GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/login 
Content-Type: application/json

{
    "username": "Antony",
    "password": "root123"
}


###
DELETE http://localhost:3001/api/blogs/64fc28c477a9b7f27a1815e7

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "AntiBus",
    "author": "Cunt d. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
    "likes": 13
}