GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs 
Content-Type: application/json

{
    "author": "Helper",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html" 
}